# -----------------------------------------------------------------------------
# Options
# -----------------------------------------------------------------------------
set -g prefix C-f
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Increase left and right status bar length to accommodate longer strings
set -g status-left-length 50
set -g status-right-length 80

# Show prefix indicator in right status bar
set -g status-right '#{?client_prefix,#[reverse] <Prefix> #[noreverse] ,}#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" %H:%M %d-%b-%y'

# -----------------------------------------------------------------------------
# Key Bindings
# -----------------------------------------------------------------------------
unbind C-b
bind C-f send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind q confirm-before -p "kill-session #S? (y/n)" kill-session
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# Use letters for choose-tree instead of numbers
bind s choose-tree -Zs -K '#{a:#{e|+:97,#{line}}}'
bind w choose-tree -Zw -K '#{a:#{e|+:97,#{line}}}'

# window hopping (allowing you to hold Ctrl while hitting prefix and n/p)
bind -r C-p previous-window
bind -r C-n next-window

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
